version: "3.4"

services:
  catalog-api:
    build:
      context: back-end/src/catalog
      dockerfile: Dockerfile
    container_name: catalog-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DbServer=sqlserver
      - DbPort=1433
      - Password=1q2w3e4r@#$
    expose:
      - "80"
    ports:
      - "7135:80"
    depends_on:
      - sqlserver

  gateway-api:
    build:
      context: back-end/src/gateway
      dockerfile: Dockerfile
    container_name: gateway-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5005:80"
    depends_on:
      - catalog-api

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r@#$"
      MSSQL_PID: developer
    ports:
      - "1433:1433"
